name       : autofs
version    : 5.1.6
release    : 4
source     :
    - https://www.kernel.org/pub/linux/daemons/autofs/v5/autofs-5.1.6.tar.xz : dddee3d9b7388ce6cb7432832dfade25b07ef68ad48dcce01cf247b26a10caef
license    : GPL-2.0-or-later
component  : system.utils
summary    : Kernel based automounter
description: |
    autofs is a kernel-based automounter for Linux. autofs is used to automatically mount filesystems on demand. After a period of inactivity set by a predefined timeout value, the auto-mounts will be unmounted.autofs allows one to provide centrally-managed, consistent file path names for users and applications, even in large, frequently changing installations.
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(libsasl2)
    - pkgconfig(libtirpc)
    - openldap-devel
setup      : |
    %configure --with-systemd \
               --with-libtirpc \
               --enable-ignore-busy \
               --without-hesiod
build      : |
    %make
install    : |
    %make_install install_samples
    rm -rf $installdir/etc/init.d
    rm -rf $installdir/run
