name       : autofs
version    : 5.1.6
release    : 7
source     :
    - https://mirrors.edge.kernel.org/pub/linux/daemons/autofs/v5/autofs-5.1.6.tar.xz : dddee3d9b7388ce6cb7432832dfade25b07ef68ad48dcce01cf247b26a10caef
license    : GPL-2.0-or-later
component  : system.utils
summary    : Kernel based automounter
description: |
    Kernel based automounter
libsplit   : no
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(libsasl2)
    - pkgconfig(libtirpc)
    - openldap-devel
environment: |
    export MAKE_OPTS="INSTALLROOT=$installdir confdir=/etc/ libdir=%libdir% systemddir=%libdir%/systemd/system/"
setup      : |
    %apply_patches
    %reconfigure --enable-ignore-busy \
               --with-libtirpc \
               --with-systemd \
               --without-hesiod
build      : |
    %make
install    : |
    %make_install $MAKE_OPTS
    %make install_samples $MAKE_OPTS
    rm -rf $installdir/etc/init.d
    rm -rf $installdir/run
