name       : autofs
version    : 5.1.3
release    : 5
source     :
    - https://www.kernel.org/pub/linux/daemons/autofs/v5/autofs-5.1.3.tar.xz : e96eebfe3ed5fb1a30f4510f538198affde223e370c6dc2bed9780309272b1bf
license    : GPL-2.0-or-later
component  : system.utils
summary    : Kernel based automounter
description: |
    Kernel based automounter
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(libsasl2)
    - pkgconfig(libtirpc)
    - openldap-devel
setup      : |
    %configure --with-systemd \
               --with-libtirpc \
               --enable-ignore-busy \
               --without-hesiod
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/etc/init.d
    rm -rf $installdir/run
